apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role # ClusterRole
metadata:
  name: server-read
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # ClusterRoleBinding
metadata:
  name: server-read-bind
subjects:
  - kind: ServiceAccount
    name: server
    namespace: prod
roleRef:
  kind: Role # ClusterRole
  name: server-read
  apiGroup: rbac.authorization.k8s.io
