apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "marcioecom/hello-go:v3"
          envFrom:
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - mountPath: "/go/src/app/myskills"
              name: config

      volumes:
        - name: config
          configMap:
            name: configmap-skills
            items:
              - key: languages
                path: "skills.txt"
